version: '3'

services:
  app1:
    image: linkacloud/vrrp-go-example
    build:
      context: .
    privileged: true
    command:
    - -log=INFO
    - -gossip-port=18888
    - -gossip-addrs=app1:18888,app2:18888
    networks:
    - vrrp
  app2:
    image: linkacloud/vrrp-go-example
    build:
      context: .
    privileged: true
    command:
    - -log=INFO
    - -gossip-port=18888
    - -gossip-addrs=app1:18888,app2:18888
    networks:
    - vrrp
  client:
    image: alpine
    restart: always
    networks:
    - vrrp
    command:
    - sh
    - -c
    - apk add curl && while true; do curl -s -m 1 172.42.0.42:8888; sleep 1; done

networks:
  vrrp:
    ipam:
      driver: default
      config:
      - subnet: 172.42.0.0/24
